export type Character = {
  id: number;
  name: string;
  crew: string;
  role: string;
  devilFruit: string | null;
  bounty: number | null;
  affiliation: string;
  description: string;
};

export const characters: Character[] = [
  {
    id: 1,
    name: "Monkey D. Luffy",
    crew: "Straw Hat Pirates",
    role: "Captain",
    devilFruit: "Gomu Gomu no Mi",
    bounty: 3000000000,
    affiliation: "Straw Hat Grand Fleet",
    description: "The captain of the Straw Hat Pirates and one of the Four Emperors.",
  },
  {
    id: 2,
    name: "Roronoa Zoro",
    crew: "Straw Hat Pirates",
    role: "Swordsman",
    devilFruit: null,
    bounty: 1111000000,
    affiliation: "Straw Hat Pirates",
    description: "A master swordsman who fights with three swords and serves as Luffy's right-hand man.",
  },
  {
    id: 3,
    name: "Nami",
    crew: "Straw Hat Pirates",
    role: "Navigator",
    devilFruit: null,
    bounty: 366000000,
    affiliation: "Straw Hat Pirates",
    description: "The navigator of the Straw Hat Pirates with an exceptional talent for cartography and weather.",
  },
  {
    id: 4,
    name: "Usopp",
    crew: "Straw Hat Pirates",
    role: "Sniper",
    devilFruit: null,
    bounty: 500000000,
    affiliation: "Straw Hat Pirates",
    description: "The Straw Hats' sniper and an inventive marksman known for his exaggerated stories.",
  },
  {
    id: 5,
    name: "Sanji",
    crew: "Straw Hat Pirates",
    role: "Cook",
    devilFruit: null,
    bounty: 1032000000,
    affiliation: "Straw Hat Pirates",
    description: "The Straw Hats' cook who specializes in powerful kicking techniques.",
  },
  {
    id: 6,
    name: "Tony Tony Chopper",
    crew: "Straw Hat Pirates",
    role: "Doctor",
    devilFruit: "Hito Hito no Mi",
    bounty: 1000,
    affiliation: "Straw Hat Pirates",
    description: "A reindeer who became a human-reindeer hybrid after eating the Human-Human Fruit.",
  },
  {
    id: 7,
    name: "Nico Robin",
    crew: "Straw Hat Pirates",
    role: "Archaeologist",
    devilFruit: "Hana Hana no Mi",
    bounty: 930000000,
    affiliation: "Straw Hat Pirates",
    description: "An archaeologist who can decipher Poneglyphs and uncover the history of the world.",
  },
  {
    id: 8,
    name: "Franky",
    crew: "Straw Hat Pirates",
    role: "Shipwright",
    devilFruit: null,
    bounty: 394000000,
    affiliation: "Straw Hat Pirates",
    description: "The Straw Hats' shipwright and a cyborg who built the Thousand Sunny.",
  },
  {
    id: 9,
    name: "Brook",
    crew: "Straw Hat Pirates",
    role: "Musician",
    devilFruit: "Yomi Yomi no Mi",
    bounty: 383000000,
    affiliation: "Straw Hat Pirates",
    description: "A living skeleton and musician who returned to life through the Revive-Revive Fruit.",
  },
  {
    id: 10,
    name: "Jinbe",
    crew: "Straw Hat Pirates",
    role: "Helmsman",
    devilFruit: null,
    bounty: 1100000000,
    affiliation: "Straw Hat Pirates",
    description: "A former Warlord of the Sea and fish-man karate master who serves as the Straw Hats' helmsman.",
  },
  {
    id: 11,
    name: "Portgas D. Ace",
    crew: "Whitebeard Pirates",
    role: "Commander",
    devilFruit: "Mera Mera no Mi",
    bounty: 550000000,
    affiliation: "Whitebeard Pirates",
    description: "The adopted brother of Luffy and former commander of the Whitebeard Pirates.",
  },
  {
    id: 12,
    name: "Sabo",
    crew: "Revolutionary Army",
    role: "Chief of Staff",
    devilFruit: "Mera Mera no Mi",
    bounty: null,
    affiliation: "Revolutionary Army",
    description: "The Revolutionary Army's chief of staff and one of Luffy's sworn brothers.",
  },
  {
    id: 13,
    name: "Shanks",
    crew: "Red Hair Pirates",
    role: "Captain",
    devilFruit: null,
    bounty: 4048900000,
    affiliation: "Four Emperors",
    description: "The captain of the Red Hair Pirates and one of the Four Emperors.",
  },
  {
    id: 14,
    name: "Marshall D. Teach",
    crew: "Blackbeard Pirates",
    role: "Captain",
    devilFruit: "Yami Yami no Mi",
    bounty: 3996000000,
    affiliation: "Four Emperors",
    description: "Known as Blackbeard, he commands the Blackbeard Pirates and possesses multiple Devil Fruit powers.",
  },
  {
    id: 15,
    name: "Edward Newgate",
    crew: "Whitebeard Pirates",
    role: "Captain",
    devilFruit: "Gura Gura no Mi",
    bounty: 5046000000,
    affiliation: "Four Emperors",
    description: "Known as Whitebeard, he was one of the strongest pirates of his era.",
  },
  {
    id: 16,
    name: "Trafalgar D. Water Law",
    crew: "Heart Pirates",
    role: "Captain",
    devilFruit: "Ope Ope no Mi",
    bounty: 3000000000,
    affiliation: "Worst Generation",
    description: "A skilled surgeon and pirate captain known as the Surgeon of Death.",
  },
  {
    id: 17,
    name: "Eustass Kid",
    crew: "Kid Pirates",
    role: "Captain",
    devilFruit: "Jiki Jiki no Mi",
    bounty: 3000000000,
    affiliation: "Worst Generation",
    description: "A magnetic Devil Fruit user and captain of the Kid Pirates.",
  },
  {
    id: 18,
    name: "Boa Hancock",
    crew: "Kuja Pirates",
    role: "Captain",
    devilFruit: "Mero Mero no Mi",
    bounty: 1659000000,
    affiliation: "Kuja Pirates",
    description: "The former Warlord of the Sea and ruler of Amazon Lily.",
  },
  {
    id: 19,
    name: "Dracule Mihawk",
    crew: "Cross Guild",
    role: "Swordsman",
    devilFruit: null,
    bounty: 3590000000,
    affiliation: "Cross Guild",
    description: "Known as the world's strongest swordsman and a former Warlord of the Sea.",
  },
  {
    id: 20,
    name: "Crocodile",
    crew: "Cross Guild",
    role: "Founder",
    devilFruit: "Suna Suna no Mi",
    bounty: 1965000000,
    affiliation: "Cross Guild",
    description: "A former Warlord and mastermind who controls the Cross Guild alongside Mihawk and Buggy.",
  },
  {
    id: 21,
    name: "Buggy",
    crew: "Cross Guild",
    role: "Emperor",
    devilFruit: "Bara Bara no Mi",
    bounty: 3189000000,
    affiliation: "Four Emperors",
    description: "A former Roger Pirates apprentice who became a Yonko and figurehead of Cross Guild.",
  },
  {
    id: 22,
    name: "Donquixote Doflamingo",
    crew: "Donquixote Pirates",
    role: "Captain",
    devilFruit: "Ito Ito no Mi",
    bounty: 340000000,
    affiliation: "Former Warlord",
    description: "A former Warlord and underworld broker who ruled Dressrosa.",
  },
  {
    id: 23,
    name: "Charlotte Linlin",
    crew: "Big Mom Pirates",
    role: "Captain",
    devilFruit: "Soru Soru no Mi",
    bounty: 4388000000,
    affiliation: "Four Emperors",
    description: "Known as Big Mom, she was captain of the Big Mom Pirates and ruler of Totto Land.",
  },
  {
    id: 24,
    name: "Kaido",
    crew: "Beasts Pirates",
    role: "Captain",
    devilFruit: "Uo Uo no Mi, Model: Seiryu",
    bounty: 4611000000,
    affiliation: "Four Emperors",
    description: "Known as the strongest creature, Kaido ruled Wano through the Beasts Pirates.",
  },
  {
    id: 25,
    name: "Yamato",
    crew: "Beasts Pirates",
    role: "Fighter",
    devilFruit: "Inu Inu no Mi, Model: Okuchi no Makami",
    bounty: null,
    affiliation: "Wano",
    description: "A powerful fighter from Wano who idolizes Kozuki Oden.",
  },
  {
    id: 26,
    name: "Marco",
    crew: "Whitebeard Pirates",
    role: "First Division Commander",
    devilFruit: "Tori Tori no Mi, Model: Phoenix",
    bounty: 1374000000,
    affiliation: "Whitebeard Pirates",
    description: "The former first division commander of the Whitebeard Pirates with phoenix abilities.",
  },
  {
    id: 27,
    name: "Charlotte Katakuri",
    crew: "Big Mom Pirates",
    role: "Sweet Commander",
    devilFruit: "Mochi Mochi no Mi",
    bounty: 1057000000,
    affiliation: "Big Mom Pirates",
    description: "One of Big Mom's strongest commanders and a master of Observation Haki.",
  },
  {
    id: 28,
    name: "King",
    crew: "Beasts Pirates",
    role: "Lead Performer",
    devilFruit: "Ryu Ryu no Mi, Model: Pteranodon",
    bounty: 1390000000,
    affiliation: "Beasts Pirates",
    description: "Kaido's right-hand man and a member of the Lunarian race.",
  },
  {
    id: 29,
    name: "Queen",
    crew: "Beasts Pirates",
    role: "Lead Performer",
    devilFruit: "Ryu Ryu no Mi, Model: Brachiosaurus",
    bounty: 1320000000,
    affiliation: "Beasts Pirates",
    description: "A scientist and one of Kaido's top commanders.",
  },
  {
    id: 30,
    name: "Rob Lucci",
    crew: "CP0",
    role: "Agent",
    devilFruit: "Neko Neko no Mi, Model: Leopard",
    bounty: null,
    affiliation: "World Government",
    description: "A highly skilled assassin and former member of CP9 who later joined CP0.",
  },
  {
    id: 31,
    name: "Koby",
    crew: "Marines",
    role: "Captain",
    devilFruit: null,
    bounty: null,
    affiliation: "Marines",
    description: "A Marine officer who began his journey as a cabin boy and trained under Garp.",
  },
  {
    id: 32,
    name: "Smoker",
    crew: "Marines",
    role: "Vice Admiral",
    devilFruit: "Moku Moku no Mi",
    bounty: null,
    affiliation: "Marines",
    description: "A Marine officer who relentlessly pursues pirates, especially Luffy.",
  },
  {
    id: 33,
    name: "Monkey D. Garp",
    crew: "Marines",
    role: "Vice Admiral",
    devilFruit: null,
    bounty: null,
    affiliation: "Marines",
    description: "A legendary Marine hero and Luffy's grandfather.",
  },
  {
    id: 34,
    name: "Sengoku",
    crew: "Marines",
    role: "Fleet Admiral",
    devilFruit: "Hito Hito no Mi, Model: Daibutsu",
    bounty: null,
    affiliation: "Marines",
    description: "A former Fleet Admiral of the Marines and legendary figure of the old era.",
  },
  {
    id: 35,
    name: "Dr. Vegapunk",
    crew: "World Government",
    role: "Scientist",
    devilFruit: "Nomi Nomi no Mi",
    bounty: null,
    affiliation: "World Government",
    description: "The world's greatest scientist whose research has transformed the technological landscape.",
  },
  {
    id: 36,
    name: "Bon Clay",
    crew: "Baroque Works",
    role: "Officer Agent",
    devilFruit: "Mane Mane no Mi",
    bounty: 32000000,
    affiliation: "Newkama Land",
    description: "A former Baroque Works agent and loyal friend of Luffy.",
  },
  {
    id: 37,
    name: "Vinsmoke Reiju",
    crew: "Germa 66",
    role: "Commander",
    devilFruit: null,
    bounty: null,
    affiliation: "Germa Kingdom",
    description: "Sanji's older sister and a genetically enhanced member of the Vinsmoke family.",
  },
  {
    id: 38,
    name: "Vinsmoke Judge",
    crew: "Germa 66",
    role: "King",
    devilFruit: null,
    bounty: null,
    affiliation: "Germa Kingdom",
    description: "The ruler of Germa Kingdom and father of Sanji.",
  },
  {
    id: 39,
    name: "Brook",
    crew: "Rumbar Pirates",
    role: "Musician",
    devilFruit: "Yomi Yomi no Mi",
    bounty: 383000000,
    affiliation: "Straw Hat Pirates",
    description: "A musician who spent decades alone before joining the Straw Hat Pirates.",
  },
  {
    id: 40,
    name: "Kin'emon",
    crew: "Nine Red Scabbards",
    role: "Samurai",
    devilFruit: "Fuku Fuku no Mi",
    bounty: null,
    affiliation: "Wano",
    description: "A samurai from Wano and one of the Nine Red Scabbards.",
  },
  {
    id: 41,
    name: "Kozuki Momonosuke",
    crew: "Kozuki Family",
    role: "Shogun",
    devilFruit: "Uo Uo no Mi, Model: Seiryu",
    bounty: null,
    affiliation: "Wano",
    description: "The heir of the Kozuki family and ruler of Wano.",
  },
  {
    id: 42,
    name: "Tashigi",
    crew: "Marines",
    role: "Captain",
    devilFruit: null,
    bounty: null,
    affiliation: "Marines",
    description: "A Marine swordswoman with a strong passion for collecting and protecting famous swords.",
  },
  {
    id: 43,
    name: "Perona",
    crew: "Thriller Bark Pirates",
    role: "Officer",
    devilFruit: "Horo Horo no Mi",
    bounty: null,
    affiliation: "Thriller Bark",
    description: "A ghost-themed Devil Fruit user who can create negative spirits.",
  },
  {
    id: 44,
    name: "Gecko Moria",
    crew: "Thriller Bark Pirates",
    role: "Captain",
    devilFruit: "Kage Kage no Mi",
    bounty: 320000000,
    affiliation: "Former Warlord",
    description: "A former Warlord who uses shadows to control zombies and steal the shadows of others.",
  },
  {
    id: 45,
    name: "Enel",
    crew: "Skypiea",
    role: "God",
    devilFruit: "Goro Goro no Mi",
    bounty: null,
    affiliation: "Skypiea",
    description: "The self-proclaimed god of Skypiea who possesses powerful lightning abilities.",
  },
  {
    id: 46,
    name: "Nefertari Vivi",
    crew: "Alabasta Kingdom",
    role: "Princess",
    devilFruit: null,
    bounty: null,
    affiliation: "Alabasta Kingdom",
    description: "The princess of Alabasta and an honorary member of the Straw Hat Pirates.",
  },
  {
    id: 47,
    name: "Boa Sandersonia",
    crew: "Kuja Pirates",
    role: "Commander",
    devilFruit: "Hebi Hebi no Mi, Model: Anaconda",
    bounty: null,
    affiliation: "Kuja Pirates",
    description: "One of Boa Hancock's younger sisters and a powerful Kuja warrior.",
  },
  {
    id: 48,
    name: "Bartolomeo",
    crew: "Barto Club",
    role: "Captain",
    devilFruit: "Bari Bari no Mi",
    bounty: 200000000,
    affiliation: "Straw Hat Grand Fleet",
    description: "A devoted fan of Luffy and captain of the Barto Club.",
  },
  {
    id: 49,
    name: "Cavendish",
    crew: "Beautiful Pirates",
    role: "Captain",
    devilFruit: null,
    bounty: 330000000,
    affiliation: "Straw Hat Grand Fleet",
    description: "A charismatic swordsman and captain of the Beautiful Pirates.",
  },
  {
    id: 50,
    name: "Don Chinjao",
    crew: "Happo Navy",
    role: "Former Leader",
    devilFruit: null,
    bounty: null,
    affiliation: "Happo Navy",
    description: "A legendary pirate and former leader of the Happo Navy.",
  },
];

export const searchCharacters = async (query: string) => {
  await new Promise((resolve) => setTimeout(resolve, 500));

  if (!query) {
    return [];
  }

  return characters.filter((character) =>
    character.name.toLowerCase().includes(query.toLowerCase())
  );
};