import { type Product } from "./ProductFilterDashboard";

export const PRODUCTS: Product[] = [
  { id: '1', name: 'Mechanical Keyboard', category: 'Electronics', price: 129 },
  { id: '2', name: 'Wireless Mouse', category: 'Electronics', price: 49 },
  { id: '3', name: 'USB-C Hub', category: 'Electronics', price: 59 },
  { id: '4', name: 'Webcam', category: 'Electronics', price: 79 },
  { id: '5', name: '27" Monitor', category: 'Electronics', price: 329 },
  { id: '6', name: 'Noise-Cancelling Headphones', category: 'Electronics', price: 249 },
  { id: '7', name: 'Portable SSD 1TB', category: 'Electronics', price: 119 },
  { id: '8', name: 'Standing Desk', category: 'Furniture', price: 399 },
  { id: '9', name: 'Ergonomic Chair', category: 'Furniture', price: 549 },
  { id: '10', name: 'Desk Lamp', category: 'Furniture', price: 39 },
  { id: '11', name: 'Monitor Arm', category: 'Furniture', price: 89 },
  { id: '12', name: 'Bookshelf', category: 'Furniture', price: 179 },
  { id: '13', name: 'Filing Cabinet', category: 'Furniture', price: 219 },
  { id: '14', name: 'Notebook Set', category: 'Stationery', price: 15 },
  { id: '15', name: 'Fountain Pen', category: 'Stationery', price: 35 },
  { id: '16', name: 'Sticky Notes Pack', category: 'Stationery', price: 8 },
  { id: '17', name: 'Highlighter Set', category: 'Stationery', price: 12 },
  { id: '18', name: 'Desk Planner', category: 'Stationery', price: 22 },
  { id: '19', name: 'Laptop Sleeve', category: 'Accessories', price: 29 },
  { id: '20', name: 'Cable Organizer', category: 'Accessories', price: 14 },
  { id: '21', name: 'Wrist Rest', category: 'Accessories', price: 18 },
  { id: '22', name: 'Laptop Stand', category: 'Accessories', price: 45 },
  { id: '23', name: 'Desk Mat', category: 'Accessories', price: 27 },
  { id: '24', name: 'Whiteboard', category: 'Office Supplies', price: 65 },
  { id: '25', name: 'Paper Shredder', category: 'Office Supplies', price: 89 },
];